-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 16:39:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pibid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pibid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pibid` DEFAULT CHARACTER SET utf8 ;
USE `pibid` ;

-- -----------------------------------------------------
-- Table `pibid`.`bolsistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsistas` (
  `idbolsistas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `telefone` VARCHAR(40) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `dataInclusao` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idbolsistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_eventos_realizados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_eventos_realizados` (
  `idbolsista_eventos_realizados` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `inicio` DATE NULL,
  `termino` DATE NULL,
  `local` VARCHAR(100) NULL,
  `descricao` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idbolsista_eventos_realizados`),
  INDEX `fk_bolsista_eventos_bolsistas_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_eventos_bolsistas`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_participacao_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_participacao_eventos` (
  `idbolsista_participacao_eventos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `inicio` VARCHAR(45) NULL,
  `termino` VARCHAR(45) NULL,
  `lcoal` VARCHAR(100) NULL,
  `bolsista_participacao_eventoscol` VARCHAR(45) NULL,
  `quantidade_bolsistas` INT NULL,
  `anexo` VARCHAR(45) NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idbolsista_participacao_eventos`),
  INDEX `fk_bolsista_participacao_eventos_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_participacao_eventos_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_capacitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_capacitacao` (
  `idbolsista_capacitacao` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(250) NULL,
  `inicio` VARCHAR(45) NULL,
  `termino` VARCHAR(45) NULL,
  `escola` VARCHAR(100) NULL,
  `publico_alvo` VARCHAR(100) NULL,
  `sintese` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_capacitacao`),
  INDEX `fk_bolsista_capacitacao_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_capacitacao_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_gincana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_gincana` (
  `idbolsista_gincana` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(200) NULL,
  `data` VARCHAR(45) NULL,
  `publico_alvo` VARCHAR(100) NULL,
  `local` VARCHAR(100) NULL,
  `sintese` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_gincana`),
  INDEX `fk_bolsista_gincana_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_gincana_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_monitorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_monitorias` (
  `idbolsista_monitorias` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NULL,
  `publico_alvo` VARCHAR(100) NULL,
  `inicio` VARCHAR(45) NULL,
  `termino` VARCHAR(45) NULL,
  `sintese` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_monitorias`),
  INDEX `fk_bolsista_monitorias_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_monitorias_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_mostra_feiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_mostra_feiras` (
  `idbolsista_mostra_feiras` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `inicio` VARCHAR(45) NULL,
  `termino` VARCHAR(45) NULL,
  `local` VARCHAR(100) NULL,
  `publico_alvo` VARCHAR(100) NULL,
  `sintese` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_mostra_feiras`),
  INDEX `fk_bolsistas_mostra_feiras_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsistas_mostra_feiras_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_visitas_tecnicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_visitas_tecnicas` (
  `idbolsista_visitas_tecnicas` INT NOT NULL AUTO_INCREMENT,
  `lcoal` VARCHAR(100) NULL,
  `objetivo` LONGTEXT NULL,
  `data` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_visitas_tecnicas`),
  INDEX `fk_bolsista_visitas_tecnicas_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_visitas_tecnicas_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_tcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_tcc` (
  `idbolsista_tcc` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL,
  `orientador` VARCHAR(200) NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_tcc`),
  INDEX `fk_bolsista_tcc_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_tcc_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_manual_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_manual_atividade` (
  `idbolsista_manual_atividade` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL,
  `descricao` LONGTEXT NULL,
  `periodo` VARCHAR(50) NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_manual_atividade`),
  INDEX `fk_bolsista_manual_atividade_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_manual_atividade_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsistas_experimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsistas_experimentos` (
  `idbolsistas_experimentos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `descricao` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsistas_experimentos`),
  INDEX `fk_bolsistas_experimentos_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsistas_experimentos_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsistas_recursos_didaticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsistas_recursos_didaticos` (
  `idbolsistas_recursos_didaticos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `descricao` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsistas_recursos_didaticos`),
  INDEX `fk_bolsistas_recursos_didaticos_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsistas_recursos_didaticos_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_producao_bibliografica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_producao_bibliografica` (
  `idbolsista_producao_bibliografica` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL,
  `tipo` VARCHAR(45) NULL,
  `referencia` VARCHAR(100) NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsista_producao_bibliograficacol` VARCHAR(45) NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_producao_bibliografica`),
  INDEX `fk_bolsista_producao_bibliografica_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_producao_bibliografica_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`bolsista_producao_artistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`bolsista_producao_artistica` (
  `idbolsista_producao_artistica` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `local` VARCHAR(100) NULL,
  `inicio` VARCHAR(45) NULL,
  `termino` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  `anexo` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `bolsistas_idbolsistas` INT NOT NULL,
  PRIMARY KEY (`idbolsista_producao_artistica`),
  INDEX `fk_bolsista_producao_artistica_bolsistas1_idx` (`bolsistas_idbolsistas` ASC),
  CONSTRAINT `fk_bolsista_producao_artistica_bolsistas1`
    FOREIGN KEY (`bolsistas_idbolsistas`)
    REFERENCES `pibid`.`bolsistas` (`idbolsistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pibid`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pibid`.`administradores` (
  `idadministradores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(250) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idadministradores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
